homework_10/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path(
        "",
        views.posts_view,
        name="index",
    ),
    path(
        "users/",
        views.users_with_posts,
        name="users-with-posts",
    ),
    path(
        "list/",
        views.PostListView.as_view(),
        name="list"
    ),
    path(
        "detail/<int:pk>/",
        views.PostDetailView.as_view(),
        name="detail"
    ),
    path(
        "create/",
        views.PostCreateView.as_view(),
        name="create"
    ),
]

homework_10/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("blog/", include("blog.urls")),
]

homework_10/blog/models.py
from django.db import models


class User(models.Model):
    class Meta:
        verbose_name_plural = "Users"

    name = models.CharField(max_length=64, unique=True)
    username = models.CharField(max_length=64, unique=True)
    email = models.CharField(max_length=64, unique=True, null=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    class Meta:
        verbose_name_plural = "Post"

    title = models.CharField(max_length=100, default="", null=False)
    body = models.TextField(max_length=200, default="", null=False)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
    )

    def __str__(self):
        return self.title

homework_10/blog/forms.py
from django import forms

from .models import Post, User


class PostForm(forms.ModelForm):
    title = forms.CharField(
        label="Заголовок поста",
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )

    body = forms.CharField(
        label="Тест поста",
        required=True,
        widget=forms.Textarea(
            attrs={
                "class": "form-control"
            }
        )
    )

    user = forms.ModelChoiceField(
        queryset=User.objects.all(),
        required=False,
        widget=forms.Select(
            attrs={
                "class": "form-control"
            }
        )
    )

    class Meta:
        model = Post
        fields = "__all__"

homework_10/blog/views.py
from django.http import HttpRequest
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView

from .models import User, Post
from .forms import PostForm


def posts_view(request: HttpRequest):
    posts = (
        Post
        .objects
        .select_related("user")
        .all()
    )
    context = {
        "posts": posts,
    }
    return render(
        request,
        "posts/posts-list.html",
        context,
    )


def users_with_posts(request: HttpRequest):
    context = {
        "users": (
            User
            .objects
            .prefetch_related("posts")
            .all()
        )
    }
    return render(
        request,
        "posts/users-with-posts.html",
        context,
    )


class PostListView(ListView):
    models = Post
    template_name = "posts/post-list.html"
    context_object_name = "posts"

    def get_queryset(self):
        return Post.objects.select_related("user").all()


class PostDetailView(DetailView):
    models = Post
    template_name = "posts/post-detail.html"

    def get_queryset(self):
        return Post.objects.select_related("user").all()


class PostCreateView(CreateView):
    models = Post
    template_name = "posts/post-create.html"
    form_class = PostForm
    success_url = reverse_lazy("blog:list")

homework_10/blog/templates/posts/post-create.html
{% extends 'base.html' %}

{% block title %}
  New Post
{% endblock %}

{% block body %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Save</button>
    </form>

  {% include 'common/footer-common.html' %}
{% endblock %}

homework_10/blog/templates/posts/post-detail.html
{% extends 'base.html' %}

{% block title %}
  {{object.title}}
{% endblock %}

{% block body %}
  <h1>{{object.title}}</h1>
    {{object.user.name}}
  <p></p>
    {{object.body}}

  {% include 'common/footer-common.html' %}
{% endblock %}

homework_10/blog/templates/posts/post-list.html
{% extends 'base.html' %}

{% block title %}
  Posts list
{% endblock %}

{% block body %}
  <h1>Posts:</h1>
  {% if posts %}
    <ul>
      {% for post in posts %}
        <li>
          <strong><a href="{% url 'blog:detail' pk=post.pk %}"> {{ post.title }}</a></strong> <em>({{ post.user.name }})</em>.
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <h2>No posts yet!</h2>
  {% endif %}
  <p></p>
  <a href="{% url 'blog:create' %}">Create</a>

  {% include 'common/footer-common.html' %}
{% endblock %}

homework_10/blog/templates/posts/posts-list.html
{% extends 'base.html' %}

{% block title %}
  Posts
{% endblock %}

{% block body %}
  <h1>Posts:</h1>
  {% if posts %}
    <ul>
      {% for post in posts %}
        <li>
          <strong>{{ post.title }}</strong> <em>({{ post.user.name }})</em>.
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <h2>No posts yet!</h2>
  {% endif %}

  {% include 'common/footer-common.html' %}
{% endblock %}

homework_10/blog/templates/posts/users-with-posts.html
{% extends 'base.html' %}

{% block title %}
  Users w/ posts
{% endblock %}

{% block body %}
  <h1>Users</h1>
  <h2>With posts</h2>

  {% if users %}
    <ul>
      {% for user in users %}
        <li>
          <strong>{{ user }}</strong>
          <ul>
            {% for post in user.posts.all %}
              <li>{{ post.title }}</li>
            {% endfor %}
          </ul>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <h3>No users yet</h3>
  {% endif %}

  {% include 'common/footer-common.html' %}
{% endblock %}

homework_10/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <title>{% block title %}
  	Base title
  {% endblock %}</title>
</head>
<body>
{% block body %}
	Base body
{% endblock %}
</body>
</html>

homework_10/templates/common/footer-common.html
<div>
  <a href="{% url 'index' %}">Back to index</a>
</div>

homework_10/templates/index.html
{% extends 'base.html' %}

{% block title %}
  Blog Homepage
{% endblock %}

{% block body %}
  <h1>Welcome to our Blog!</h1>
  <ul>
    <li><a href="{% url 'blog:index' %}"
    >Posts</a></li>
    <li><a href="{% url 'blog:users-with-posts' %}"
    >Users</a></li>
    <li><a href="{% url 'blog:list' %}">Posts list</a>
      </li>
  </ul>
{% endblock %}